import re
import time  # Для пауз
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://test.online.bima.tj/")
    time.sleep(0.5)  # Пауза в 0.5 секунды

    page.get_by_role("navigation").get_by_role("button").click()
    time.sleep(0.3)
    page.get_by_role("link", name="Клиентам").click()
    time.sleep(0.3)
    page.get_by_role("button", name=">").click()
    time.sleep(0.3)
    page.get_by_role("button", name="<").click()
    time.sleep(0.3)
    page.get_by_role("button", name=">").click()
    time.sleep(0.3)
    page.get_by_role("button", name=">").click()
    time.sleep(0.3)
    page.get_by_role("navigation").get_by_role("button").click()
    time.sleep(0.3)
    page.get_by_role("link", name="Клиентам").click()
    time.sleep(0.3)
    page.get_by_role("navigation").get_by_role("button").click()
    time.sleep(0.3)
    page.get_by_role("link", name="Автострахование").click()
    time.sleep(0.3)
    page.locator(".slider-products__link").first.click()
    time.sleep(0.3)
    page.get_by_placeholder("Иванов Алексей Петрович").click()
    time.sleep(0.3)
    page.get_by_placeholder("Иванов Алексей Петрович").fill("Test")
    time.sleep(0.3)
    page.get_by_placeholder("Иванов Алексей Петрович").press("Tab")
    time.sleep(0.3)
    page.get_by_placeholder("(992) 00-000-").fill("(992) 76-876-78678")
    time.sleep(0.3)
    page.get_by_text("--------").first.click()
    time.sleep(0.3)
    page.get_by_text("Таджикский паспорт").click()
    time.sleep(0.3)
    page.get_by_placeholder("AA", exact=True).click()
    time.sleep(0.3)
    page.get_by_placeholder("AA", exact=True).fill("AA")
    time.sleep(0.3)
    page.get_by_placeholder("123123123").click()
    time.sleep(0.3)
    page.get_by_placeholder("123123123").fill("12345678")
    time.sleep(0.3)
    page.get_by_text("--------").click()
    time.sleep(0.3)
    page.get_by_text("2022", exact=True).click()
    time.sleep(0.3)
    page.get_by_placeholder("1234AA01").click()
    time.sleep(0.3)
    page.get_by_placeholder("1234AA01").fill("1212AA12")
    time.sleep(0.3)
    page.locator("label").filter(
        has_text="Я согласен(-на) с условиями обработки персональных данных и правилами пользовани").locator(
        "span").click()
    time.sleep(0.3)
    page.locator("label").filter(has_text="Я подтверждаю, что автомобиль не используется в качестве такси").locator(
        "span").click()
    time.sleep(0.3)
    page.locator("label").filter(has_text="Я подтверждаю, что водительский стаж составляет более 1").locator(
        "span").click()
    time.sleep(0.3)
    page.get_by_placeholder("Иванов Алексей Петрович").click()
    time.sleep(0.3)
    page.get_by_placeholder("Иванов Алексей Петрович").click()
    time.sleep(0.3)
    page.get_by_placeholder("Иванов Алексей Петрович").fill("Test Test")
    time.sleep(0.3)
    page.get_by_role("button", name="К оформлению").click()
    time.sleep(0.3)
    page.locator("label").filter(has_text="Visa/MasterCard/Мир").locator("div").click()
    time.sleep(0.3)
    page.locator("label").filter(has_text="Visa/MasterCard/Мир").click()
    time.sleep(0.3)
    page.get_by_role("button", name="Оплатить").click()
    time.sleep(0.3)

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
