import re
import time  # Для пауз
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://test.online.bima.tj/")
    time.sleep(0.5)  # Пауза в 0.5 секунды

    page.get_by_role("navigation").get_by_role("button").click()
    time.sleep(0.5)
    page.get_by_role("link", name="Для путешественников").click()
    time.sleep(0.5)
    page.locator("#root svg").click()
    time.sleep(0.5)
    page.locator("#react-select-2-option-0").click()
    time.sleep(0.5)
    page.locator("label").filter(has_text="На одну поездкуПолис действует на одну поездку").locator("div span").click()
    time.sleep(0.5)
    page.locator("label").filter(has_text="На несколько поездокПолис, который позволяет путешествовать несколько раз в тече").locator("div span").click()
    time.sleep(0.5)
    page.locator("label").filter(has_text="На одну поездкуПолис действует на одну поездку").locator("div span").click()
    time.sleep(0.5)
    page.locator("div").filter(has_text=re.compile(r"^Дата рождения\*Неверно заполнено$")).get_by_role("textbox").fill("1999-12-12")
    time.sleep(0.5)
    page.get_by_text("--------", exact=True).click()
    time.sleep(0.5)
    page.get_by_text("Женский").click()
    time.sleep(0.5)
    page.get_by_text("-----------").click()
    time.sleep(0.5)
    page.locator("div").filter(has_text=re.compile(r"^Дата вылета\*$")).get_by_placeholder("ДД / ММ / ГГГГ").fill("2025-01-01")
    time.sleep(0.5)
    page.locator("div").filter(has_text=re.compile(r"^Дата прилета\*$")).get_by_placeholder("ДД / ММ / ГГГГ").fill("2025-01-04")
    time.sleep(0.5)
    page.get_by_placeholder("Количество дней").click()
    time.sleep(0.5)
    page.get_by_text("-----------").click()
    time.sleep(0.5)
    page.get_by_text("Спокойный отдых", exact=True).click()
    time.sleep(0.5)
    page.get_by_role("button", name="К оформлению").click()
    time.sleep(0.5)
    page.get_by_text("1 путешественник").click()
    time.sleep(0.5)
    page.get_by_text("1 путешественник").click()
    time.sleep(0.5)
    page.get_by_text("000").first.click()
    time.sleep(0.5)
    page.locator("div").filter(has_text=re.compile(r"^75 000$")).click()
    time.sleep(0.5)
    page.get_by_role("button", name="EUR").click()
    time.sleep(0.5)
    page.get_by_role("button", name="Далее").click()
    time.sleep(0.5)
    page.locator("label").filter(has_text="Солнечные ожоги").locator("span").click()
    time.sleep(0.5)
    page.locator("label").filter(has_text="Осложнение беременности").locator("span").click()
    time.sleep(0.5)
    page.locator("label").filter(has_text="Личные вещи").locator("span").click()
    time.sleep(0.5)
    page.locator("label").filter(has_text="Контакты с морскими гадами").locator("span").click()
    time.sleep(0.5)
    page.locator("label").filter(has_text="Алкогольное опьянение").locator("span").click()
    time.sleep(0.5)
    page.get_by_role("button", name="Далее").click()
    time.sleep(0.5)
    page.locator("#holderFullName").click()
    time.sleep(0.5)
    page.locator("#holderFullName").fill("Test Test")
    time.sleep(0.5)
    page.get_by_placeholder("(992) 00-000-").click()
    time.sleep(0.5)
    page.get_by_placeholder("(992) 00-000-").fill("(992) 97-878-86686")
    time.sleep(0.5)
    page.get_by_placeholder("(992) 00-000-").press("Tab")
    time.sleep(0.5)
    page.get_by_placeholder("mail@mail.ru").fill("Test@bima.tj")
    time.sleep(0.5)
    page.locator("input[type=\"date\"]").first.fill("1999-12-12")
    time.sleep(0.5)
    page.locator("#holderDocSeries").click()
    time.sleep(0.5)
    page.locator("div").filter(has_text=re.compile(r"^Серия паспортаНеверно заполнено$")).first.click()
    time.sleep(0.5)
    page.locator("input[type=\"date\"]").first.fill("1999-02-12")
    time.sleep(0.5)
    page.locator("#holderDocSeries").click()
    time.sleep(0.5)
    page.locator("#holderDocSeries").fill("AA")
    time.sleep(0.5)
    page.locator("#holderDocNumber").click()
    time.sleep(0.5)
    page.locator("#holderDocNumber").fill("12345678")
    time.sleep(0.5)
    page.get_by_text("--------").first.click()
    time.sleep(0.5)
    page.get_by_text("Таджикский загран. паспорт").first.click()
    time.sleep(0.5)
    page.locator("input[type=\"date\"]").nth(1).fill("2024-12-27")
    time.sleep(0.5)
    page.locator("#holderIssueInstitution").click()
    time.sleep(0.5)
    page.locator("#holderIssueInstitution").fill("Testvydan")
    time.sleep(0.5)
    page.get_by_placeholder("Адрес регистрации").click()
    time.sleep(0.5)
    page.get_by_placeholder("Адрес регистрации").fill("Testadress")
    time.sleep(0.5)
    page.get_by_text("Скопировать информацию о страхователе").click()
    time.sleep(0.5)
    page.get_by_placeholder("Адрес дома").click()
    time.sleep(0.5)
    page.get_by_placeholder("Адрес дома").fill("Dushanbe, teststreet")
    time.sleep(0.5)
    page.locator("label").filter(has_text="Я согласен(-на) с условиями обработки персональных данных и правилами пользовани").locator("span").click()
    time.sleep(0.5)
    page.get_by_role("button", name="Далее").click()
    time.sleep(0.5)
    page.get_by_role("button", name="К оформлению").click()
    time.sleep(0.5)
    page.locator("label").filter(has_text="КОРТИ МИЛЛИ").click()
    time.sleep(0.5)
    page.get_by_role("button", name="Оплатить").click()
    time.sleep(0.5)

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
